[package]
name = "termgame"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
smallvec = "1.13.2"
micromap = "0.0.15"
rand = "0.8.5"

[profile.release]
#strip = true
lto = true
codegen-units = 1