[package]
name = "termgame"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
smallvec = "1.13.2"
micromap = "0.0.15"
rand = "0.8.5"
anymap = "0.12.1"
noise = "0.9.0"

[profile.release]
# for size:
#strip = true
#opt-level = 'z'

# for performance:
#lto = true
#codegen-units = 1
