[workspace]
members = [
    "teng",
    "termill",
]

resolver = "2"

default-members = ["termill", "teng"]

[profile.release]
# for size:
#strip = true
#opt-level = 'z'

# for performance:
#lto = true
#codegen-units = 1
